version: '3.9'

services:
    mininet:
        image: containernet/containernet
        container_name: containernet
        environment:
            - CONFIG_IP_SCTP=y
        pid: "host"
        cap_add:
            - ALL
        command: /bin/bash
        privileged: true
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "/lib/modules:/lib/modules"
